### ISSUE TITLE
meet android.support.v4.content not exist

### ISSUE THREAD

**Issue by reply-1988** [PonnamKarthik/FlutterToast#53]
after i update to 2.2.8, i meet the following errors.
/Users/reply/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.2.8/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java:14: 错误: 程序包android.support.v4.content不存在
import android.support.v4.content.ContextCompat;
                                 ^
/Users/reply/flutter/.pub-cache/hosted/pub.flutter-io.cn/fluttertoast-2.2.8/android/src/main/java/io/github/ponnamkarthik/toast/fluttertoast/FluttertoastPlugin.java:108: 错误: 找不到符号
          Drawable shapeDrawable = ContextCompat.getDrawable(ctx, R.drawable.toast_bg);
                                   ^
  符号:   变量 ContextCompat
  位置: 类 FluttertoastPlugin
2 个错误

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':fluttertoast:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 5s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by PonnamKarthik** [comment]
I was unable to replicate the issue

can you please try adding

`implementation 'com.android.support:support-compat:27.1.1'` 

in build.gradle and try

**Comment by reply-1988** [comment]
@PonnamKarthik i had solved this problem, i use Android X in the project.
I delete `android.useAndroidX=true` and 
`android.enableJetifier=true` solve it.
thank you.
