### ISSUE TITLE
MethodCallHandlerImpl - Build failed

### ISSUE THREAD

**Issue by Mariluk** [ponnamkarthik/FlutterToast#300]
I got this error after update from 8.0.3 to 8.0.5.

`
e: /home/maril/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.0.4/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (17, 16): Redeclaration: MethodCallHandlerImpl
e: /home/maril/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.0.5/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (21, 16): Redeclaration: MethodCallHandlerImpl
e: /home/maril/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.0.5/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (129, 28): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?                                                                 
FAILURE: Build failed with an exception.                                                                                                     
 What went wrong:                                                      
Execution failed for task ':fluttertoast:compileReleaseKotlin'.         
 Compilation error. See log for more details                           
Try:                                                                  
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
 Get more help at https://help.gradle.org                              
BUILD FAILED in 2m 14s  
 `

8.0.3 is OK.

**Comment by mstrkn** [comment]
I have same error with 8.0.5

**Comment by romater0** [comment]
Same error as well on upgrading ; )

**Comment by tkeithblack** [comment]
Same:
Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type View?

**Comment by nguyenxdat** [comment]
Same here

**Comment by changshuai7** [comment]
same error.....

**Comment by Hopheylalal** [comment]
same error

**Comment by YouChuantong** [comment]
After I updated the flitter to 2.0.5, an error occurred when I started the Android project in MacOS. IOS runs smoothly (Windows runs Android smoothly). The error is as follows:
``` log
e: /usr/local/Caskroom/flutter/2.0.2/flutter/.pub-cache/hosted/  pub.dartlang.org/fluttertoast  -8.0.5/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/M  ethodCallHandlerImpl.kt  : (129, 28): Only safe (?.)  or non-null asserted (!!.)  calls are allowed on a nullable receiver of type View?
```

**Comment by nguyenxdat** [comment]
Change 
`fluttertoast:
           git:
              url: https://github.com/ponnamkarthik/FlutterToast.git
              ref: master`

**Comment by alr2413** [comment]
@nguyenxdat,
if you fixed this issue, please create a PR.
thanks

**Comment by ponnamkarthik** [comment]
Fixed in `8.0.6`

**Comment by Mariluk** [comment]
Still have.
`
e: /home/maril/snap/flutter/common/flutter/.pub-cache/hosted/pub.dartlang.org/fluttertoast-8.0.6/android/src/main/kotlin/io/github/ponnamkarthik/toast/fluttertoast/MethodCallHandlerImpl.kt: (21, 16): Redeclaration: MethodCallHandlerImpl                                                                      
FAILURE: Build failed with an exception
.   `

**Comment by thivankasarathchandra** [comment]
@Mariluk  try a flutter clean. I had that same thing in 8.0.6. But a flutter clean fixed it for me.

**Comment by mstrkn** [comment]
@Mariluk same. A flutter clean fixed it.

**Comment by Mariluk** [comment]
Yea sry .. flutter clean fixed it. :)

**Comment by tkeithblack** [comment]
Fixed here too. Thanks!
